openapi: 3.0.0
x-stoplight:
  id: zvdgj65zna2j5
info:
  title: Anime-Service
  version: '1.0'
  contact:
    name: <Contact Person>
    url: https://opensource.org/license/mit/
    email: x@gmail.com
  license:
    url: http://localhost:3000
    name: MIT
  termsOfService: http://localhost:3000
  description: 'Service for aquiring information on Anime. Uses Anilist API to aquire it, but holds some information (ex. User-Anime information like reviews) in a dedicated database.'
servers:
  - url: http://localhost:3000
paths:
  '/anime/{animeId}':
    parameters:
      - schema:
          type: integer
          format: int64
          minimum: 1
        name: animeId
        in: path
        required: true
        description: The Anilist ID of the anime
    get:
      summary: Get Anime details
      tags:
        - External Communication
        - User information
        - Keycloak
      responses:
        '200':
          description: OK - The Anilist server responded correctly and no other errors occured.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/DetailedAnimeDTO'
              examples:
                Successfull example:
                  value:
                    externalInformation:
                      id: 123987
                      season: SPRING
                      seasonYear: 2021
                      episodes: 12
                      duration: 25
                      genres:
                        - MECHA
                        - ROMANCE
                      averageScore: 95
                      format: TV
                      type: ANIME
                      favourites: 59687
                      isAdult: true
                      title:
                        english: English Title
                        romaji: Romaji Title
                        native: Native Title
                      status: FINISHED
                      coverImage:
                        extraLarge: LinkToExtraLarge
                        large: LinkToLarge
                        medium: LinkToMedium
                        color: LinkToColor
                      description: Some Description
                      source: ORIGINAL
                      startDate:
                        year: 2021
                        month: 1
                        day: 18
                      endDate:
                        year: 2021
                        month: 1
                        day: 18
                      nextAiringEpisode:
                        id: 6325
                        airingAt: 184585
                        timeUntilAiring: 60504
                        episode: 10
                        mediaId: 123987
                      relations:
                        edges:
                          - node:
                              id: 123
                              type: MANGA
                              title:
                                english: English Title
                                romaji: Romaji Title
                                native: Native Title
                              coverImage:
                                extraLarge: LinkToExtraLarge
                                large: LinkToLarge
                                medium: LinkToMedium
                                color: LinkToColor
                              status: FINISHED
                          - id: 7895
                          - relationType: ADAPTATION
                      characters:
                        edges:
                          - node:
                              id: 963
                              image:
                                large: LinkToLarge
                                medium: LinkToMedium
                              name:
                                first: FirstName
                                middle: MiddleName
                                last: LastName
                                full: FullName
                                native: NativeName
                                alternative: AlternativeName
                                alternativeSpoiler: AlternativeNameWithSpoiler
                            id: 78965
                            role: MAIN
                            name: CharacterName
                            voiceActors:
                              - id: 78654
                                name:
                                  first: Kacper
                                  middle: Damian
                                  last: Curys
                                  full: Kacper Damian Curys
                                  native: Kacper Damian Curyś
                                image:
                                  large: LinkToLarge
                                  medium: LinkToMedium
                                languageV2: JAPANESE
                        pageInfo:
                          total: 50
                          perPage: 25
                          currentPage: 1
                          lastPage: 50
                          hasNextPage: true
                      staff:
                        nodes:
                          - name:
                              first: Kacper
                              middle: Damian
                              last: Curys
                              full: Kacper Damian Curys
                              native: Kacper Damian Curyś
                            image:
                              large: LinkToLarge
                              medium: LinkToMedium
                            primaryOccupation:
                              - Voice Actor
                        pageInfo:
                          total: 10
                          perPage: 50
                          currentPage: 10
                          lastPage: 10
                          hasNextPage: false
                    localAnimeInformation:
                      animeId: 165794
                      title: title
                      averageScore: 8.7
                      nrOfFavourites: 10
                      nrOfReviews: 3
                    localAnimeReviews:
                      - reviewType: simpleReview
                        id: 1
                        title: The Review Title
                        text: The Review text
                        nrOfUpvotes: 10
                        nrOfDownvotes: 3
                        nrOfHelpfull: 8
                        modification: '2019-08-24T14:15:22Z'
                    localUserAnimeInformation:
                      id:
                        userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                        animeId: 165794
                      status: NO_STATUS
                      watchStartDate: '2019-08-24'
                      watchEndDate: '2019-08-24'
                      nrOfEpisodesSeen: 5
                      isFavourite: true
                      modification: '2019-08-24T14:15:22Z'
                      grade: 2
                      review:
                        reviewType: simpleReview
                        id: 1
                        title: The Review Title
                        text: The Review text
                        nrOfUpvotes: 10
                        nrOfDownvotes: 3
                        nrOfHelpfull: 8
                        modification: '2019-08-24T14:15:22Z'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Validation Error:
                  value:
                    message: Please contact the administration
                    status: 500
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
        '503':
          description: Service Unavailable - the Anilist service returned an error or didn't return anything.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Anilist Error Example:
                  value:
                    message: Anilist Error Message
                    status: 503
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
      operationId: get-anime-by-id
      x-stoplight:
        id: yoy4agyvnughd
      description: 'Get detailed Anime information using it''s ID. If the Authorization Token is logged in during the request, user specific data is added to the response.'
      security:
        - Keycloak_JWT: []
      parameters: []
  '/anime/ranking/{rankingType}/{pageNumber}':
    parameters:
      - schema:
          type: string
          $ref: './Models.yaml#/components/schemas/RankingType'
        name: rankingType
        in: path
        required: true
        description: Which ranking should be retrived
      - schema:
          type: integer
          $ref: './Models.yaml#/components/schemas/PageNumber'
        name: pageNumber
        in: path
        required: true
        description: Number of the page to be retrieved
    get:
      summary: Get ranking page result
      tags:
        - External Communication
      responses:
        '200':
          description: OK - The Anilist server responded correctly and no other errors occured.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/AnilistPageDTO'
              examples:
                Successfull Example:
                  value:
                    media:
                      - id: 789654
                        coverImage:
                          extraLarge: LinkToCoverImage
                          large: LinkToLarge
                          medium: LinkToMedium
                          color: LinkToColor
                        title:
                          english: EnglishTitle
                          romaji: RomajiTitle
                          native: NativeTitle
                    pageInfo:
                      total: 10
                      perPage: 5
                      currentPage: 1
                      lastPage: 10
                      hasNextPage: true
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Validation Error:
                  value:
                    message: Please contact the administration
                    status: 500
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
        '503':
          description: Service Unavailable - the Anilist service returned an error or didn't return anything.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Anilist Error Example:
                  value:
                    message: Anilist Error Message
                    status: 503
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
      operationId: get-anime-by-ranking
      x-stoplight:
        id: nupswuymp998u
      description: 'Get a page of Anime from a selected ranking, ex. Best of all Time.'
  '/anime/search/{pageNumber}':
    parameters:
      - schema:
          type: integer
          $ref: './Models.yaml#/components/schemas/PageNumber'
        name: pageNumber
        in: path
        required: true
        description: Number of the page to be retrieved
    get:
      summary: Get query page result
      tags:
        - External Communication
      responses:
        '200':
          description: OK - The Anilist server responded correctly and no other errors occured.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/AnilistPageDTO'
              examples:
                Successfull Example:
                  value:
                    media:
                      - id: 789654
                        coverImage:
                          extraLarge: LinkToCoverImage
                          large: LinkToLarge
                          medium: LinkToMedium
                          color: LinkToColor
                        title:
                          english: EnglishTitle
                          romaji: RomajiTitle
                          native: NativeTitle
                    pageInfo:
                      total: 10
                      perPage: 5
                      currentPage: 1
                      lastPage: 10
                      hasNextPage: true
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Validation Error:
                  value:
                    message: Please contact the administration
                    status: 500
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
        '503':
          description: Service Unavailable - the Anilist service returned an error or didn't return anything.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Anilist Error Example:
                  value:
                    message: Anilist Error Message
                    status: 503
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
      operationId: search-for-anime-using-query
      x-stoplight:
        id: 66y83jnxmaj01
      description: Get a page of Anime that meet the conditons in the query.
      security:
        - Keycloak_JWT: []
      parameters:
        -   schema:
                type: string
            in: query
            name: title
            description: Phrase that should be in the Anime title
        -   schema:
                type: string
                format: date
            in: query
            name: maxStartDate
            description: Maximum date of airing of the Anime
        -   schema:
                type: string
                format: date
            in: query
            name: minStartDate
            description: Minimum date of airing of the Anime
        -   schema:
                type: string
                format: date
            in: query
            name: maxEndDate
            description: Maximum date of finishing of the Anime
        -   schema:
                type: string
                format: date
            in: query
            description: Minimum date of finishing of the Anime
            name: minEndDate
        -   schema:
                type: integer
                minimum: 0
            in: query
            name: maxNumberOfEpisodes
            description: Maximum number of episodes of the Anime
        -   schema:
                type: integer
                minimum: 0
            in: query
            name: minNumberOfEpisodes
            description: Minimum number of episodes of the Anime
        -   schema:
                type: integer
                minimum: 0
                maximum: 100
            in: query
            name: maxAverageScore
            description: Maximum average score in Anilist Service
        -   schema:
                type: integer
                minimum: 0
                maximum: 100
            in: query
            name: minAverageScore
            description: Mininum average score in Anilist Service
        -   schema:
                type: integer
                minimum: 1900
                example: 1901
            in: query
            name: seasonYear
            description: What year did the anime air
  /anime/userInformation:
    put:
      summary: Update user-anime information
      operationId: update-user-anime-information
      responses:
        '200':
          description: OK - The backend responds with the updated information.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/LocalUserAnimeInformationDTO'
              examples:
                Successfull Example:
                  value:
                    id:
                      userId: 2c4a230c-5085-4924-a3e1-25fb4fc5965b
                      animeId: 195784
                    status: NO_STATUS
                    watchStartDate: '2019-08-24'
                    watchEndDate: '2019-08-24'
                    nrOfEpisodesSeen: 5
                    isFavourite: true
                    modification: '2019-08-24T14:15:22Z'
                    grade: 2
                    review:
                      reviewType: simpleReview
                      id: 1
                      title: The Review Title
                      text: The Review text
                      nrOfUpvotes: 10
                      nrOfDownvotes: 3
                      nrOfHelpfull: 8
                      modification: '2019-08-24T14:15:22Z'
        '401':
          description: Unauthorized - The user didn't authenticate correctly
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Unauthenticated Error Example:
                  value:
                    message: Authentication Error
                    status: 401
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
        '409':
          description: Conflict - User tried to update the data of another User
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Conflict Error Example:
                  value:
                    message: Conflict Error
                    status: 409
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
        '422':
          description: Unprocessable Entity - Some error was found in the DTO. Ex. the review text is too long.
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Unprocessable Entity Error Example:
                  value:
                    message: Unprocessable Entity Error
                    status: 422
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: './Models.yaml#/components/schemas/ErrorDTO'
              examples:
                Validation Error:
                  value:
                    message: Please contact the administration
                    status: 500
                    timestamp: '2019-08-24T14:15:22Z'
                    code: 3af3fb4d-5baf-4748-9a29-747d2f81b381
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './Models.yaml#/components/schemas/LocalUserAnimeInformationDTO'
            examples:
              Anime User Information Example:
                value:
                  id:
                    userId: 3af3fb4d-5baf-4748-9a29-747d2f81b381
                    animeId: 195784
                  status: NO_STATUS
                  watchStartDate: '2019-08-24'
                  watchEndDate: '2019-08-24'
                  nrOfEpisodesSeen: 5
                  isFavourite: true
                  modification: '2019-08-24T14:15:22Z'
                  grade: 2
                  review:
                    reviewType: simpleReview
                    id: 1
                    title: The Review Title
                    text: The Review text
                    nrOfUpvotes: 10
                    nrOfDownvotes: 3
                    nrOfHelpfull: 8
                    modification: '2019-08-24T14:15:22Z'
        description: The DTO contains information on an Anime by a local user.
      x-stoplight:
        id: fjsmctviprg25
      tags:
        - Keycloak
        - Achievements Earnable
      description: Endpoint for updating user-anime information like reviews or grade.
      security:
        - Keycloak_JWT: []
components:
  securitySchemes:
    Keycloak_JWT:
      type: http
      scheme: bearer
      description: 'Authentication used by all microservices, aquired from a Keycloak Service'
  parameters:
      season:
          schema:
              $ref: './Models.yaml#/components/schemas/AnilistMediaSeason'
          in: query
          name: season
          description: What season did the Anime air
      status:
          schema:
              $ref: './Models.yaml#/components/schemas/AnilistMediaStatus'
          in: query
          name: status
          description: What is the Anilist status of the Anime
      format:
          schema:
              $ref: './Models.yaml#/components/schemas/AnilistMediaFormat'
          in: query
          name: format
          description: What was the format of the Anime
security:
  - Keycloak_JWT: []
tags:
  - name: Achievements Earnable
    description: 'Depending on user actions, achievements can be earned'
  - name: External Communication
    description: This microservice/endpoint communicates with an external API
  - name: Keycloak
    description: This microservice/endpoint uses Keycloak for authorization
  - name: User information
    description: This endpoint will return some sort of user information
